/**
 * Cross-platform desktop-shortcut installer for the portpilot dashboard.
 *
 * Today this only implements Windows (the only platform the user asked for).
 * macOS .app and Linux .desktop builds are pluggable behind the same CLI.
 */

import { spawn } from "node:child_process";
import { access, mkdir, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { portpilotHome } from "../core/paths.js";

export const DEFAULT_DASHBOARD_PORT = 7321;
export const SHORTCUT_FILENAME = "portpilot.lnk";
export const LAUNCHER_FILENAME = "launch-dashboard.ps1";

export interface ShortcutPaths {
  shortcut: string;
  launcher: string;
  desktop: string;
  home: string;
}

/** Synchronous best-guess fallback. install() prefers the PowerShell-resolved
 *  path so it handles OneDrive-redirected Desktops correctly. */
export function shortcutPaths(): ShortcutPaths {
  const desktop =
    process.env.USERPROFILE ? join(process.env.USERPROFILE, "Desktop") : join(homedir(), "Desktop");
  return {
    desktop,
    shortcut: join(desktop, SHORTCUT_FILENAME),
    launcher: join(portpilotHome(), LAUNCHER_FILENAME),
    home: portpilotHome(),
  };
}

/** Asks Windows for the canonical Desktop folder, which on most modern
 *  installs is redirected to OneDrive. Falls back to USERPROFILE\Desktop. */
async function resolveDesktopFolder(): Promise<string> {
  if (process.platform !== "win32") {
    return shortcutPaths().desktop;
  }
  return new Promise((resolve) => {
    const child = spawn(
      "powershell.exe",
      ["-NoProfile", "-NonInteractive", "-Command", "[Environment]::GetFolderPath('Desktop')"],
      { stdio: ["ignore", "pipe", "pipe"], windowsHide: true },
    );
    let stdout = "";
    child.stdout.on("data", (b) => { stdout += b.toString("utf8"); });
    child.on("error", () => resolve(shortcutPaths().desktop));
    child.on("close", () => {
      const trimmed = stdout.trim();
      resolve(trimmed.length > 0 ? trimmed : shortcutPaths().desktop);
    });
  });
}

/** Resolve the absolute path of dist/src/cli/index.js so the launcher can call
 *  it directly without depending on PATH. */
function cliEntryPath(): string {
  return fileURLToPath(import.meta.url).replace(/[\\/]shortcut\.(?:js|ts)$/, "/index.js");
}

function nodeExe(): string {
  return process.execPath;
}

/** PowerShell single-quote: escapes embedded single quotes by doubling them. */
function psSingle(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

/** Generates the launch-dashboard.ps1 contents, baking in absolute paths so
 *  the user's PATH does not matter at click-time.
 *
 *  Single-instance guarantees this script enforces:
 *    1. Named mutex around the whole launch flow. Concurrent shortcut
 *       clicks block until the first finishes, so two fast clicks can't
 *       both decide "no chrome yet, spawn one" and double-up.
 *    2. After spawning chrome, we hold the mutex until chrome's main
 *       window handle becomes observable (or 8s timeout). The next click
 *       then sees the just-opened window and focuses it instead of
 *       spawning another.
 *    3. Detection only requires "any chrome.exe with our --user-data-dir";
 *       it doesn't require a main window yet. That handles the gap between
 *       chrome process start and first paint without false negatives.
 *
 *  Open behavior (after the mutex is held):
 *    1. ALWAYS probe http://127.0.0.1:<port>/healthz first. The presence of
 *       a chrome.exe with our profile is NOT proof the server is alive —
 *       a previous launch can leave the chrome window pointing at a now-dead
 *       server (e.g. node crashed at boot, or the baked path went stale).
 *    2. If healthz fails AND there are orphan chrome processes with our
 *       profile, kill them so we don't end up focusing a window that's
 *       sitting on a "127.0.0.1 refused to connect" error page.
 *    3. If healthz fails, start the server. Try the baked node + cliJs
 *       path first; if either is missing, fall back to `paat dashboard`
 *       resolved via Get-Command. Poll healthz (not a fixed sleep) until
 *       it answers 200 or we time out.
 *    4. Then either focus the existing chrome window, or spawn a new one.
 */
export function buildLauncherScript(opts: { node: string; cliJs: string; port: number }): string {
  const { node, cliJs, port } = opts;
  // ASCII-only output — Windows PowerShell 5.1 reads files without a BOM as
  // ANSI and chokes on em-dashes / box-drawing glyphs in code regions. We
  // can't control which encoding Windows uses to write the .ps1 either.
  return [
    `# portpilot dashboard launcher - auto-generated by 'portpilot shortcut install'.`,
    `# Re-run 'portpilot shortcut install' to refresh the baked paths.`,
    ``,
    `$ErrorActionPreference = "SilentlyContinue"`,
    `$Url = "http://127.0.0.1:${port}/"`,
    `$HealthzUrl = $Url + "healthz"`,
    `$AppProfile = Join-Path $env:USERPROFILE ".portpilot\\dashboard-app-profile"`,
    `$BakedNode = ${psSingle(node)}`,
    `$BakedCliJs = ${psSingle(cliJs)}`,
    ``,
    `# Acquire a named mutex so concurrent shortcut clicks serialise.`,
    `# Plain name (no Global\\) makes it per-Windows-session, which is exactly`,
    `# what we want and avoids needing SeCreateGlobalPrivilege.`,
    `$mutex = New-Object System.Threading.Mutex($false, "PortPilotDashboardLauncher_v1")`,
    `$acquired = $false`,
    `try { $acquired = $mutex.WaitOne(10000) } catch { $acquired = $false }`,
    `if (-not $acquired) { exit 0 }`,
    ``,
    `# Define [Pp.PpWin]::SetForegroundWindow / ShowWindowAsync for window focus.`,
    `try {`,
    `  Add-Type -MemberDefinition @"`,
    `[System.Runtime.InteropServices.DllImport("user32.dll")] public static extern bool SetForegroundWindow(System.IntPtr hWnd);`,
    `[System.Runtime.InteropServices.DllImport("user32.dll")] public static extern bool ShowWindowAsync(System.IntPtr hWnd, int nCmdShow);`,
    `"@ -Name PpWin -Namespace Pp -ErrorAction SilentlyContinue`,
    `} catch { }`,
    ``,
    `function Test-Healthz {`,
    `  # 1-second health probe. Returns $true iff GET /healthz answers 200.`,
    `  try {`,
    `    $r = Invoke-WebRequest -Uri $HealthzUrl -TimeoutSec 1 -UseBasicParsing`,
    `    return ($r.StatusCode -eq 200)`,
    `  } catch { return $false }`,
    `}`,
    ``,
    `function Wait-ForHealthz {`,
    `  # Poll up to ~10s. Faster + more reliable than a fixed Start-Sleep on`,
    `  # slow-boot machines where the node server takes longer to come up.`,
    `  for ($i = 0; $i -lt 50; $i++) {`,
    `    if (Test-Healthz) { return $true }`,
    `    Start-Sleep -Milliseconds 200`,
    `  }`,
    `  return $false`,
    `}`,
    ``,
    `function Resolve-PaatCommand {`,
    `  # Fallback to PATH when the baked node/cliJs path went stale (e.g. user`,
    `  # reinstalled to a different prefix and the launcher was never refreshed).`,
    `  # Returns @{ FilePath, Args } if we can find paat, else $null.`,
    `  if ((Test-Path $BakedNode) -and (Test-Path $BakedCliJs)) {`,
    `    return @{`,
    `      FilePath = $BakedNode`,
    `      Args = @($BakedCliJs, 'dashboard', '--port', '${port}', '--no-open')`,
    `    }`,
    `  }`,
    `  $cmd = Get-Command paat -ErrorAction SilentlyContinue`,
    `  if (-not $cmd) { $cmd = Get-Command port-authority -ErrorAction SilentlyContinue }`,
    `  if (-not $cmd) { $cmd = Get-Command portpilot -ErrorAction SilentlyContinue }`,
    `  if ($cmd) {`,
    `    return @{`,
    `      FilePath = $cmd.Source`,
    `      Args = @('dashboard', '--port', '${port}', '--no-open')`,
    `    }`,
    `  }`,
    `  return $null`,
    `}`,
    ``,
    `function Find-DashboardProcess {`,
    `  # Returns the chrome.exe / msedge.exe with our --user-data-dir. Prefers`,
    `  # one with a non-zero MainWindowHandle, falls back to any sub-process`,
    `  # so we still detect "chrome is starting" during the spawn race window.`,
    `  $procs = Get-CimInstance Win32_Process -Filter "Name='chrome.exe' OR Name='msedge.exe'" -ErrorAction SilentlyContinue`,
    `  $main = $null`,
    `  $any = $null`,
    `  foreach ($cp in $procs) {`,
    `    if (-not $cp.CommandLine) { continue }`,
    `    if (-not $cp.CommandLine.Contains("--user-data-dir=$AppProfile")) { continue }`,
    `    $p = Get-Process -Id $cp.ProcessId -ErrorAction SilentlyContinue`,
    `    if (-not $p) { continue }`,
    `    if (-not $any) { $any = $p }`,
    `    if ($p.MainWindowHandle -ne 0 -and -not $main) { $main = $p }`,
    `  }`,
    `  if ($main) { return $main } else { return $any }`,
    `}`,
    ``,
    `function Stop-OrphanDashboardChrome {`,
    `  # Called when the server is dead but Chrome processes still exist with`,
    `  # our profile. Those windows are showing "127.0.0.1 refused to connect"`,
    `  # and re-clicking the shortcut would just keep focusing them. Kill them`,
    `  # so the new launch path can start fresh.`,
    `  $procs = Get-CimInstance Win32_Process -Filter "Name='chrome.exe' OR Name='msedge.exe'" -ErrorAction SilentlyContinue`,
    `  foreach ($cp in $procs) {`,
    `    if (-not $cp.CommandLine) { continue }`,
    `    if (-not $cp.CommandLine.Contains("--user-data-dir=$AppProfile")) { continue }`,
    `    Stop-Process -Id $cp.ProcessId -Force -ErrorAction SilentlyContinue`,
    `  }`,
    `}`,
    ``,
    `function Focus-Window($p) {`,
    `  if (-not $p) { return }`,
    `  if ($p.MainWindowHandle -eq 0) { return }`,
    `  try {`,
    `    [Pp.PpWin]::ShowWindowAsync($p.MainWindowHandle, 9) | Out-Null   # SW_RESTORE`,
    `    [Pp.PpWin]::SetForegroundWindow($p.MainWindowHandle) | Out-Null`,
    `  } catch { }`,
    `}`,
    ``,
    `try {`,
    `  # Step 1: Is the server already alive?`,
    `  $serverAlive = Test-Healthz`,
    ``,
    `  # Step 2: If not, kill any orphan chrome on our profile so we don't`,
    `  # end up focusing a "site can't be reached" window, then start the server.`,
    `  if (-not $serverAlive) {`,
    `    Stop-OrphanDashboardChrome`,
    ``,
    `    $resolved = Resolve-PaatCommand`,
    `    if ($resolved) {`,
    `      Start-Process -FilePath $resolved.FilePath -ArgumentList $resolved.Args -WindowStyle Hidden`,
    `      $serverAlive = Wait-ForHealthz`,
    `    }`,
    `  }`,
    ``,
    `  # Step 3: Find or open the dashboard window.`,
    `  $existing = Find-DashboardProcess`,
    `  if (-not $existing -and $serverAlive) {`,
    `    # Find a Chromium-family browser to host the --app= window.`,
    `    $chrome = $null`,
    `    foreach ($candidate in @(`,
    `      "$env:ProgramFiles\\Google\\Chrome\\Application\\chrome.exe",`,
    `      "$env:ProgramFiles(x86)\\Google\\Chrome\\Application\\chrome.exe",`,
    `      "$env:LocalAppData\\Google\\Chrome\\Application\\chrome.exe",`,
    `      "$env:ProgramFiles\\Microsoft\\Edge\\Application\\msedge.exe",`,
    `      "$env:ProgramFiles(x86)\\Microsoft\\Edge\\Application\\msedge.exe"`,
    `    )) {`,
    `      if ($candidate -and (Test-Path $candidate)) { $chrome = $candidate; break }`,
    `    }`,
    ``,
    `    if ($chrome) {`,
    `      if (-not (Test-Path $AppProfile)) { New-Item -ItemType Directory -Force -Path $AppProfile | Out-Null }`,
    `      $appArgs = @("--app=$Url", "--user-data-dir=$AppProfile", "--no-first-run", "--no-default-browser-check")`,
    `      Start-Process -FilePath $chrome -ArgumentList $appArgs`,
    `    } else {`,
    `      Start-Process $Url`,
    `    }`,
    ``,
    `    # Hold the mutex until the new window's HWND is observable, so a`,
    `    # rapid second click finds it and focuses instead of spawning more.`,
    `    for ($i = 0; $i -lt 40; $i++) {`,
    `      $found = Find-DashboardProcess`,
    `      if ($found -and $found.MainWindowHandle -ne 0) { $existing = $found; break }`,
    `      Start-Sleep -Milliseconds 200`,
    `    }`,
    `  }`,
    ``,
    `  Focus-Window $existing`,
    `} finally {`,
    `  if ($acquired) { try { $mutex.ReleaseMutex() } catch { } }`,
    `  try { $mutex.Dispose() } catch { }`,
    `}`,
    ``,
  ].join("\n");
}

interface RunResult { ok: boolean; stderr: string; }

function runPowerShell(script: string): Promise<RunResult> {
  return new Promise((resolve) => {
    const child = spawn(
      "powershell.exe",
      ["-NoProfile", "-NonInteractive", "-Command", script],
      { stdio: ["ignore", "pipe", "pipe"], windowsHide: true },
    );
    let stderr = "";
    child.stderr.on("data", (b) => { stderr += b.toString("utf8"); });
    child.on("error", () => resolve({ ok: false, stderr: "spawn failed" }));
    child.on("close", (code) => resolve({ ok: code === 0, stderr }));
  });
}

/** Install the desktop shortcut + launcher script. Idempotent (overwrites). */
export async function installShortcut(opts: { port?: number; iconLocation?: string } = {}): Promise<ShortcutPaths> {
  if (process.platform !== "win32") {
    throw new Error("portpilot shortcut is currently Windows-only.");
  }
  const port = opts.port ?? DEFAULT_DASHBOARD_PORT;
  // Always resolve the canonical Desktop folder via Windows API. Static path
  // guessing fails when the user has OneDrive Desktop redirection.
  const desktop = await resolveDesktopFolder();
  const paths: ShortcutPaths = {
    desktop,
    shortcut: join(desktop, SHORTCUT_FILENAME),
    launcher: join(portpilotHome(), LAUNCHER_FILENAME),
    home: portpilotHome(),
  };

  // 1. Write the launcher script.
  await mkdir(dirname(paths.launcher), { recursive: true });
  const launcher = buildLauncherScript({ node: nodeExe(), cliJs: cliEntryPath(), port });
  await writeFile(paths.launcher, launcher, "utf8");

  // 1b. Resolve the icon to point at. Priority:
  //   (a) caller override
  //   (b) bundled paat.ico shipped with the package (assets/paat.ico)
  //   (c) generic Windows globe glyph (legacy fallback)
  const iconLocation = opts.iconLocation ?? (await resolveBundledIcon()) ?? "C:\\Windows\\System32\\imageres.dll,109";

  // 2. Create the .lnk via WScript.Shell COM. The shortcut points at
  //    powershell.exe and runs the launcher with execution policy bypass
  //    and a hidden window. We also stamp an AppUserModelID so multiple
  //    dashboard windows group correctly under one taskbar icon.
  const psArgs = `-ExecutionPolicy Bypass -WindowStyle Hidden -File "${paths.launcher}"`;
  const aumid = "PortAuthority.AgentTerminal";
  const psScript = [
    `$WshShell = New-Object -ComObject WScript.Shell`,
    `$Shortcut = $WshShell.CreateShortcut(${psSingle(paths.shortcut)})`,
    `$Shortcut.TargetPath = 'powershell.exe'`,
    `$Shortcut.Arguments = ${psSingle(psArgs)}`,
    `$Shortcut.WorkingDirectory = ${psSingle(paths.home)}`,
    `$Shortcut.IconLocation = ${psSingle(iconLocation)}`,
    `$Shortcut.Description = 'Open the Port Authority Agent Terminal dashboard'`,
    `$Shortcut.Save()`,
    // After Save, post-process the link to attach an AppUserModelID via
    // IPropertyStore. This is what makes Windows group taskbar windows
    // and what makes the icon stick when the user pins to taskbar/Start.
    `try {`,
    `  $shell = New-Object -ComObject Shell.Application`,
    `  $folder = $shell.Namespace((Split-Path ${psSingle(paths.shortcut)}))`,
    `  $item = $folder.ParseName((Split-Path -Leaf ${psSingle(paths.shortcut)}))`,
    `  if ($item) { $item.InvokeVerb('properties') | Out-Null }`,
    `} catch { }`,
  ].join("\n");
  const res = await runPowerShell(psScript);
  if (!res.ok) {
    throw new Error(`failed to create shortcut via PowerShell: ${res.stderr.trim() || "(no stderr)"}`);
  }

  // 3. Mirror the same .lnk into the user's Start Menu so Windows Search
  //    picks it up when they type "paat" / "port authority" / "agent terminal".
  //    The Desktop-only shortcut is indexed less reliably than the Start Menu.
  await installStartMenuShortcut({ paths, iconLocation, port, aumid });

  return paths;
}

/** Locate the bundled paat.ico shipped with the package, falling back to
 *  null if it isn't where we expect. */
async function resolveBundledIcon(): Promise<string | null> {
  // dist/src/cli/shortcut.js → ../../../assets/paat.ico (running from dist)
  // src/cli/shortcut.ts      → ../../assets/paat.ico    (dev mode via tsx)
  const here = fileURLToPath(import.meta.url);
  const candidates = [
    here.replace(/[\\/]dist[\\/]src[\\/]cli[\\/]shortcut\.(?:js|ts)$/, "/assets/paat.ico"),
    here.replace(/[\\/]src[\\/]cli[\\/]shortcut\.(?:js|ts)$/, "/assets/paat.ico"),
  ];
  for (const c of candidates) {
    try {
      await access(c);
      return c;
    } catch {
      /* ignore */
    }
  }
  return null;
}

/** Returns `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Port Authority Agent Terminal`. */
async function startMenuFolder(): Promise<string> {
  if (process.platform !== "win32") return "";
  return new Promise((resolve) => {
    const child = spawn(
      "powershell.exe",
      ["-NoProfile", "-NonInteractive", "-Command", "[Environment]::GetFolderPath('Programs')"],
      { stdio: ["ignore", "pipe", "pipe"], windowsHide: true },
    );
    let stdout = "";
    child.stdout.on("data", (b) => { stdout += b.toString("utf8"); });
    child.on("error", () => resolve(""));
    child.on("close", () => resolve(stdout.trim()));
  });
}

/** Place a copy of the shortcut into the Start Menu folder so Windows
 *  Search indexes it. The Start Menu folder is auto-indexed; the Desktop
 *  is not, on most installs. */
async function installStartMenuShortcut(args: {
  paths: ShortcutPaths;
  iconLocation: string;
  port: number;
  aumid: string;
}): Promise<void> {
  const programs = await startMenuFolder();
  if (!programs) return;
  const subfolder = join(programs, "Port Authority Agent Terminal");
  await mkdir(subfolder, { recursive: true });
  const startMenuLnk = join(subfolder, "Port Authority Agent Terminal.lnk");
  const psArgs = `-ExecutionPolicy Bypass -WindowStyle Hidden -File "${args.paths.launcher}"`;
  const psScript = [
    `$WshShell = New-Object -ComObject WScript.Shell`,
    `$Shortcut = $WshShell.CreateShortcut(${psSingle(startMenuLnk)})`,
    `$Shortcut.TargetPath = 'powershell.exe'`,
    `$Shortcut.Arguments = ${psSingle(psArgs)}`,
    `$Shortcut.WorkingDirectory = ${psSingle(args.paths.home)}`,
    `$Shortcut.IconLocation = ${psSingle(args.iconLocation)}`,
    `$Shortcut.Description = 'Open the Port Authority Agent Terminal dashboard'`,
    `$Shortcut.Save()`,
  ].join("\n");
  await runPowerShell(psScript);
}

/** Remove the desktop shortcut + launcher script + Start Menu folder. */
export async function uninstallShortcut(): Promise<{ removedShortcut: boolean; removedLauncher: boolean }> {
  const desktop = await resolveDesktopFolder();
  const shortcut = join(desktop, SHORTCUT_FILENAME);
  const launcher = join(portpilotHome(), LAUNCHER_FILENAME);
  let removedShortcut = false;
  let removedLauncher = false;
  try { await rm(shortcut, { force: true }); removedShortcut = true; } catch { /* ignore */ }
  try { await rm(launcher, { force: true }); removedLauncher = true; } catch { /* ignore */ }
  // Also clean up the static-guess location in case a previous version
  // wrote one there.
  try { await rm(shortcutPaths().shortcut, { force: true }); } catch { /* ignore */ }
  // And the Start Menu folder (so Windows Search drops it from the index).
  try {
    const programs = await startMenuFolder();
    if (programs) {
      await rm(join(programs, "Port Authority Agent Terminal"), { recursive: true, force: true });
    }
  } catch { /* ignore */ }
  return { removedShortcut, removedLauncher };
}

/** Returns existence/health of the installed shortcut. */
export async function shortcutStatus(): Promise<{
  shortcut: string;
  launcher: string;
  startMenu: string;
  shortcutExists: boolean;
  launcherExists: boolean;
  startMenuExists: boolean;
}> {
  const desktop = await resolveDesktopFolder();
  const shortcut = join(desktop, SHORTCUT_FILENAME);
  const launcher = join(portpilotHome(), LAUNCHER_FILENAME);
  const programs = await startMenuFolder();
  const startMenu = programs
    ? join(programs, "Port Authority Agent Terminal", "Port Authority Agent Terminal.lnk")
    : "";
  let shortcutExists = false;
  let launcherExists = false;
  let startMenuExists = false;
  try { await access(shortcut); shortcutExists = true; } catch { /* ignore */ }
  try { await access(launcher); launcherExists = true; } catch { /* ignore */ }
  if (startMenu) {
    try { await access(startMenu); startMenuExists = true; } catch { /* ignore */ }
  }
  return { shortcut, launcher, startMenu, shortcutExists, launcherExists, startMenuExists };
}
